# Generated by Django 5.0.1 on 2024-01-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=255, verbose_name='Exercicio')),
                ('video_id_youtube', models.CharField(max_length=255, verbose_name='Video id')),
                ('info', models.CharField(default='...', max_length=255, null=True, verbose_name='Informacão')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagem')),
                ('video_id_didatico', models.CharField(default=1, max_length=50, verbose_name='Video id didatico')),
            ],
        ),
    ]
