# Generated by Django 5.0.1 on 2024-01-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='exercicio',
            new_name='video_nome',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='info',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='informacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Informacão'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='video_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='video_url'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_id_didatico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Video id didatico'),
        ),
    ]
