# Generated by Django 5.0.1 on 2024-01-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_rename_exercicio_videomodel_video_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_videos/%Y/%m/%d', verbose_name='Imagem'),
        ),
    ]
