# Generated by Django 5.0.1 on 2024-01-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_alter_videomodel_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=255, verbose_name='Equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMuscularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_muscular', models.CharField(max_length=255, verbose_name='Grupo Musucular')),
            ],
        ),
        migrations.AddField(
            model_name='videomodel',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.equipamentomodel', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='grupo_muscular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.grupomuscularmodel', verbose_name='Grupo Muscular'),
        ),
    ]
