# Generated by Django 5.0.1 on 2024-01-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_equipamentomodel_grupomuscularmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamentomodel',
            options={'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='grupomuscularmodel',
            options={'verbose_name': 'Grupo Muscular', 'verbose_name_plural': 'Grupos Musculares'},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.equipamentomodel', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='grupo_muscular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.grupomuscularmodel', verbose_name='Grupo Muscular'),
        ),
    ]
