# Generated by Django 5.0.1 on 2024-01-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_treinomodel_treinovideosmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treinomodel',
            options={'verbose_name': 'Treino', 'verbose_name_plural': 'Treinos'},
        ),
        migrations.AlterModelOptions(
            name='treinovideosmodel',
            options={'verbose_name': 'Treino Video', 'verbose_name_plural': 'Treinos Videos'},
        ),
        migrations.AddField(
            model_name='treinovideosmodel',
            name='ordem',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
