# Generated by Django 5.0.1 on 2024-01-19 19:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_alter_treinomodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='treinovideosmodel',
            unique_together={('usuario', 'treino')},
        ),
    ]
