# Generated by Django 5.0.1 on 2024-01-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0008_alter_treinovideosmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='treinovideosmodel',
            unique_together=set(),
        ),
    ]
