# Generated by Django 5.0.1 on 2024-01-22 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_alter_treinovideosmodel_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='treinomodel',
            unique_together={('usuario', 'treino_nome')},
        ),
        migrations.AlterUniqueTogether(
            name='treinovideosmodel',
            unique_together={('usuario', 'treino')},
        ),
    ]
