# Generated by Django 5.0.1 on 2024-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_alter_treinomodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinovideosmodel',
            name='ordem',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
