# Generated by Django 5.0.1 on 2024-02-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_alter_treinovideosmodel_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
