# Generated by Django 5.0.1 on 2024-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0012_videomodel_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinosCompartilhadosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treino', models.CharField(max_length=40, verbose_name='Treino')),
                ('ordem', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('videos', models.ManyToManyField(to='academia.videomodel')),
            ],
            options={
                'verbose_name': 'Treino Compartilhado',
                'verbose_name_plural': 'Treinos compartilhados',
            },
        ),
    ]
