# Generated by Django 5.0.1 on 2024-02-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0013_treinoscompartilhadosmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinovideosmodel',
            name='slug_compartinhada',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
