# Generated by Django 5.0.1 on 2024-02-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0014_treinovideosmodel_slug_compartinhada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treinovideosmodel',
            old_name='slug_compartinhada',
            new_name='slug_compartilhado',
        ),
    ]
